<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<link name="world"/>

  <joint name="fixed_base" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
  </joint>

  <xacro:property name="base_length" value="0.6" />
  <xacro:property name="base_width" value="0.4" />
  <xacro:property name="base_height" value="0.2" />
  <xacro:property name="radius" value="0.05" />
  <xacro:property name="link_len" value="0.25" />
  <xacro:property name="shoulder_radius" value="0.1" />
  <xacro:property name="shoulder_len" value="0.3" />
  <xacro:property name="deg_90" value="1.5708" />

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
      <material name="green"/>
    </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="5.0" x="${base_length}" y="${base_width}" z="${base_height}" 
                           o_xyz="0 0 ${base_height / 2.0}" o_rpy="0 0 0" />
  </link>


  <xacro:macro name="create_cylinder_link" params="name r l origin_xyz origin_rpy">
    <link name="${name}">
      <visual>
        <geometry>
          <cylinder radius="${r}" length="${l}"/>
        </geometry>
        <origin xyz="${origin_xyz}" rpy="${origin_rpy}"/>
        <material name="gray"/>
      </visual>
            <collision>
                <geometry>
                    <cylinder radius="${r}" length="${l}" />
                </geometry>
                <origin xyz="${origin_xyz}" rpy="${origin_rpy}" />
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${r}" l="${l}" 
                                    o_xyz="0 0 0" o_rpy="${pi / 2.0} 0 0" />
    </link>
  </xacro:macro>


  <xacro:create_cylinder_link name="shoulder_link" r="${shoulder_radius}" l="${shoulder_len}" origin_xyz="0 0 0" origin_rpy="0 0 0"/>

  <joint name="base_shoulder_joint" type="prismatic">
    <parent link="base_link"/>
    <child link="shoulder_link"/>
    <origin xyz="0 0 0.2" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="0" upper="0.14" velocity="10" effort="1000"/>
  </joint>

  <xacro:create_cylinder_link name="arm_link" r="${radius}" l="${link_len}" origin_xyz="0 0 0.1" origin_rpy="0 0 0" />

  <joint name="arm_joint" type="revolute">
    <parent link="shoulder_link"/>
    <child link="arm_link"/>
    <origin xyz="0 0 0.15" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-2.1" upper="2.1" velocity="10" effort="10"/>
  </joint>

  <xacro:create_cylinder_link name="link3" r="${radius}" l="${link_len}" origin_xyz="0 0 0.125" origin_rpy="0 0 0" />

  <joint name="joint3" type="revolute">
    <parent link="arm_link"/>
    <child link="link3"/>
    <origin xyz="0 0 0.2" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-2.3" upper="2.3" velocity="10" effort="10"/>
  </joint>


</robot>
